# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0002_auto_20150812_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, default=None, null=True, verbose_name='IP address'),
        ),
    ]
