# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0003_auto_20160105_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglog',
            name='path',
            field=models.CharField(db_index=True, max_length=1024, verbose_name='path'),
        ),
    ]
