# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0004_auto_20160105_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
    ]
